version: v1
name: wf-profile-ott-contract
type: workflow
tags:
  - dataos.ott
description: The job performs profiling on top of ottchurn contract data
workflow:
  title: contract Profiler
  dag:
    - name: profile-ottchurn-contract
      title: contract Data Profiler
      description: The job performs profiling on contract data
      spec:
        tags:
          - dataos.ott
        stack: flare:3.0
        compute: runnable-default
        title: contract Data Profiler
        persistentVolume:
          name: persistent-v
          directory: fides
        flare:
          job:
            explain: true
            inputs:
              - name: contract_input
                dataset: dataos://icebase:telecom_ottchurn/ott_contract
                format: iceberg
            logLevel: info
            profile:
              level: basic
          sparkConf:
            - spark.sql.shuffle.partitions: 10
            - spark.default.parallelism: 10