version: v1
name: wf-profile-ott-complaints
type: workflow
tags:
  - ott
  - complaint
description: The job performs profiling on top of ottchurn complaints data
workflow:
  title: complaints Profiler
  dag:
    - name: profile-ottchurn-complaints
      title: complaints Data Profiler
      description: The job performs profiling on complaints data
      spec:
        tags:
          - complaint
          - ottchurn
        stack: flare:3.0
        compute: runnable-default
        title: complaints Data Profiler
        persistentVolume:
          name: persistent-v
          directory: fides
        flare:
          job:
            explain: true
            inputs:
              - name: complaints_input
                dataset: dataos://icebase:telco_ott/ott_complaints
                format: iceberg
            logLevel: info
            profile:
              level: basic
          sparkConf:
            - spark.sql.shuffle.partitions: 10
            - spark.default.parallelism: 10