version: v1
name: wf-profile-ott-userdata
type: workflow
tags:
  - ott
  - user
description: The job performs profiling on top of ottchurn userdata data
workflow:
  title: userdata Profiler
  dag:
    - name: profile-ottchurn-userdata
      title: userdata Data Profiler
      description: The job performs profiling on userdata data
      spec:
        tags:
          - user
          - ott
        stack: flare:3.0
        compute: runnable-default
        title: Depot Data Profiler
        persistentVolume:
          name: persistent-v
          directory: fides
        flare:
          job:
            explain: true
            inputs:
              - name: userdata_input
                dataset: dataos://icebase:ott_churn/ott_userdata
                format: iceberg
            logLevel: info
            profile:
              level: basic
          sparkConf:
            - spark.sql.shuffle.partitions: 10
            - spark.default.parallelism: 10