version: v1
name: wf-ott-contract
type: workflow
tags:
    - ott.contract

description: This job extracting OTT contracts stored in Blog storage and seamlessly transferring them into Icebase
workflow:
  title: OTT Contract Load
  dag:
    - name: ott-contract
      title: OTT contract Dataset
      description:  This job extracting OTT contracts stored in Blog storage and seamlessly transferring them into Icebase
      spec:
        tags:
          - ott.contract
        stack: flare:4.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 6000m
            cores: 2
            memory: 8000m
          executor:
            coreLimit: 6000m
            cores: 2
            instances: 2
            memory: 8000m   
          job:
            explain: true
            inputs:
              - name: contract_input
                dataset: dataos://thirdparty01:none/analytics/ott/Contracts.csv
                format: csv
                options:
                 header: True
                 inferschema: True

            logLevel: INFO
            outputs:
              - name: contract
                dataset: dataos://icebase:telecom_ottchurn/ott_contract?acl=rw
                format: Iceberg
                options:
                  saveMode: overwrite
            steps:
              - sequence:
                  - name: contract
                    sql:  >
                      select * from contract_input
                    functions:
                      - name: cleanse_column_names
                      - name: change_column_case
                        case: lower

                      - name: any_timestamp
                        column: contract_effective_date
                        asColumn: contract_effective_date
                         
                      - name: any_timestamp
                        column: contract_end_date
                        asColumn: contract_end_date    

    - name: dataos-tool-ottcontract
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_contract?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-contract