version: v1
name: wf-ott-players
type: workflow
tags:
  - dataos.ott
description: The Job Ingests OTT player from bigquery
workflow:
  title: OTT player load
  #schedule:                         
   # cron: "0 */1 * * *"
    #concurrencyPolicy: Forbid 
  dag:
    - name: ott-player
      title: OTT player Dataset
      spec:
        tags:
          - dataos.ott
        stack: flare:3.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 1200m
            cores: 1
            memory: 1024m
          executor:
            coreLimit: 1200m    
            cores: 1
            instances: 1
            memory: 1024m
          job:
            explain: true
            streaming:
              batchMode: true
              triggerMode: Once
              checkpointLocation: dataos://icebase:sys01/checkpoint/ott-churn-player/test/player-injest-00004?acl=rw
            inputs:
              - name: player_input
                dataset: dataos://ottbigquery:player/playertable
            logLevel: INFO
            outputs:
              - name: player
                dataset: dataos://icebase:telecom_ottchurn/ott_player?acl=rw
                format: Iceberg
                description: This dataset gives details of all OTT player and their corresponding attributes.
                tags:
                  - dataos.ott
                title: OTT player Data
                options:
                  saveMode: overwrite
                  sort:
                    mode: partition
                    columns:
                      - name: session_start
                        order: desc 
                  iceberg:
                    partitionSpec:
                        - type: day
                          column: session_start
                          name: day
                    properties:
                      write.format.default: parquet
                      write.metadata.compression-codec: gzip
            steps:
              - sequence:
                  - name: player
                    doc: Pick all the columns from player input table, perform some transformations and load to icebase
                    sql: >
                      select * from player_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower
                      - name: any_timestamp
                        column: session_start
                        asColumn: session_start
    - name: dataos-tool-ottplayer
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_player?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-player