version: v1
name: wf-ott-complaints
type: workflow
workspace: public
description:  The Job Ingests OTT complaints from redshift
tags:
  - complaint
  - ott
workflow:
  title: OTT complaints load
  dag:
    - name: ott-complaints
      title: OTT complaints Dataset
      description: This job ingest data of OTT complaints from redshift to icebase
      spec:
        tags:
          - depot
          - ott churn
        stack: flare:3.0
        compute: runnable-default
        flare:
          job:
            inputs:
              - name: complaints_input
                dataset: dataos://rsottchurn:public/complaints
                format: redshift
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:ott_churn?acl=rw
            steps:
              - sink:
                  - sequenceName: complaints
                    datasetName: ott_complaints
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset gives details of all OTT complaints and their corresponding attributes.
                    title: OTT complaint Data
                    tags:
                      - ott
                      - complaint
                    outputOptions:
                      saveMode: overwrite
                sequence:
                  - name: complaints
                    sql: >
                      select * from complaints_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower
    - name: dataos-tool-complaints
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:ott_churn/ott_complaints?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-complaints
