version: v1
name: wf-ott-billing
type: workflow
workspace: public
description:  The Job Ingests OTT billing from GBQ
tags:
  - dataos.ott
workflow:
  title: OTT billing load
  dag:
    - name: ott-billing
      title: OTT billing Dataset
      description: This job ingest data of OTT billing from GBQ to icebase
      spec:
        tags:
          - dataos.ott
        stack: flare:3.0
        compute: runnable-default
        flare:
          job:
            inputs:
              - name: billing_input
                dataset: dataos://ottbigquery:billing/billingtable
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:telecom_ottchurn?acl=rw
            steps:
              - sink:
                  - sequenceName: billing
                    datasetName: ott_billing
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset gives details of all OTT billing and their corresponding attributes
                    title: OTT billing Data
                    tags:
                      - dataos.ott
                    outputOptions:
                      saveMode: overwrite
                sequence:
                  - name: billing
                    sql: >
                      select * from billing_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower
    - name: dataos-tool-ottbilling
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_billing?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-billing
 