version: v1
name: wf-ott-contract-02
type: workflow
workspace: public
description:  The Job Ingests OTT contract from S3
tags:
  - contract
  - ott
workflow:
  title: OTT contract load
  dag:
    - name: ott-contract
      title: OTT contract Dataset
      description: This job ingest data of OTT contract from S3 to icebase
      spec:
        tags:
          - depot
          - ott churn
        stack: flare:3.0
        compute: runnable-default
        flare:
          job:
            inputs:
              - name: contract_input
                dataset: dataos://ottbigquery:contract/contractable
                format: csv
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:telco_ott?acl=rw
            steps:
              - sink:
                  - sequenceName: contract
                    datasetName: ott_contract
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset giv.es details of all OTT contract and their corresponding attributes.
                    title: OTT contract Data
                    tags:
                      - ott
                      - contract
                    outputOptions:
                      saveMode: overwrite
                sequence:
                  - name: contract
                    sql: >
                      select * from contract_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower
    - name: dataos-tool-ottcontract
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telco_ott/ott_contract?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-contract