version: v1
name: wf-ott-b2bdatas
type: workflow
tags:
    - ott.b2bdata

description: The Job Ingests OTT B2B data from Blob storage to Icebase
workflow:
  title: OTT b2bdata load
  dag:
    - name: ott-b2bdata
      title: OTT b2bdata Dataset
      description:  The Job Ingests OTT B2B data from Blob storage to Icebase
      spec:
        tags:
          - ott.b2bdata
        stack: flare:4.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 6000m
            cores: 2
            memory: 8000m
          executor:
            coreLimit: 6000m
            cores: 2
            instances: 2
            memory: 8000m   
          job:
            explain: true
            inputs:
              - name: b2bdata_input
                dataset: dataos://thirdparty01:none/analytics/ott/B2B_Data.csv
                format: csv
                options:
                 header: True
                 inferschema: True

            logLevel: INFO
            outputs:
              - name: b2bdata
                dataset: dataos://icebase:telecom_ottchurn/ott_b2bdata?acl=rw
                format: Iceberg
                options:
                  saveMode: overwrite
            steps:
              - sequence:
                  - name: b2bdata
                    sql:  >
                      select * from b2bdata_input
                    functions:
                      - name: cleanse_column_names
                      - name: change_column_case
                        case: lower

    - name: dataos-tool-ottb2bdata
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_b2bdata?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-b2bdata