version: v1
name: wf-ott-userdata
type: workflow
workspace: public
description:  The Job Ingests OTT userdata from bigquery
tags:
  - userdata
  - ott
workflow:
  title: OTT userdata load
  dag:
    - name: ott-userdata
      title: OTT userdata Dataset
      description: This job ingest data of OTT userdata from BQ to icebase
      spec:
        tags:
          - depot
          - ott churn
        stack: flare:3.0
        compute: runnable-default
        flare:
          job:
            inputs:
              - name: userdata_input
                dataset: dataos://ottbigquery:userdata/usertable
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:ott_churn?acl=rw
            steps:
              - sink:
                  - sequenceName: userdata
                    datasetName: ott_userdata
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset gives details of all OTT userdata and their corresponding attributes.
                    title: OTT userdata Data
                    tags:
                      - ott
                      - user
                    outputOptions:
                      saveMode: overwrite
                sequence:
                  - name: userdata
                    sql: >
                      select * from userdata_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower
                      - name: set_type
                        columns: 
                          dob: timestamp
                          mobile_number: int
                          start_date: timestamp
                          validity_end: timestamp
    - name: dataos-tool-ottuserdata
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:ott_churn/ott_userdata?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-userdata
