version: v1
name: wf-ott-player
type: workflow
workspace: public
description:  The Job Ingests OTT player from bigquery
tags:
  - dataos.ott
workflow:
  title: OTT player load
 # schedule:                         
  #  cron: "0 */1 * * *"
   # concurrencyPolicy: Forbid 
  dag:
    - name: ott-player
      title: OTT player Dataset
      description: This job ingest data of OTT player from BQ to icebase
      spec:
        tags:
          - dataos.ott
        stack: flare:3.0
        compute: runnable-default
      flare:
          driver:
              coreLimit: 1200m
              cores: 1
              memory: 1024m
          executor:
              coreLimit: 1200m    
              cores: 1
              instances: 1
              memory: 1024m
          job:
            explain: true
            streaming:
              batchMode: true
              triggerMode: Once
              checkpointLocation: dataos://icebase:sys01/checkpoint/ott-churn-player/test/player-injest-00002?acl=rw
            inputs:
              - name: player_input
                dataset: dataos://ottbigquery:player/playertable
                format: csv
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:telecom_ottchurn?acl=rw
            steps:
              - sink:
                  - sequenceName: player
                    datasetName: ott_player
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset gives details of all OTT player and their corresponding attributes.
                    title: OTT player Data
                    tags:
                      - dataos.ott
                    outputOptions:
                      saveMode: append
                      iceberg:
                        partitionSpec:
                          - type: identity
                            column: event_type
                          - type: month
                            column: session_start
                            name: month_partitioned
                        properties:
                          write.format.default: parquet
                          write.metadata.compression-codec: gzip
                sequence:
                  - name: player
                    sql: >
                      select * from player_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower
                      - name: any_timestamp
                        column: session_start
                        asColumn: session_start
    - name: dataos-tool-ottplayer
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_player?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-player