version: v1
name: wf-ott-userdataltd
type: workflow
workspace: public
description:  The Job Ingests OTT userdata from bigquery
tags:
  - dataosltd.ott
workflow:
  title: OTT userdata load
  dag:
    - name: ott-userdata
      title: OTT userdata Dataset
      description: This job ingest data of OTT userdata from BQ to icebase
      spec:
        tags:
          - dataosltd.ott
        stack: flare:3.0
        compute: runnable-default
        flare:
          job:
            inputs:
              - name: userdata_input
                dataset: dataos://ottbigquery:userdata/usertable
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:telecomltd_ottchurn?acl=rw
            steps:
              - sink:
                  - sequenceName: userdata
                    datasetName: ott_userdatasetltd
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset gives details of all OTT userdata and their corresponding attributes
                    title: OTT userdata Data
                    tags:
                      - dataosltd.ott
                    outputOptions:
                      saveMode: overwrite
                sequence:
                  - name: userdata
                    sql: 
                      select * from userdata_input limit 700
                    functions:
                       - name: snake_case
                       - name: change_column_case
                         case: lower
                       - name: any_timestamp
                         column: dob
                         asColumn: dob

                       - name: any_timestamp
                         column: start_date
                         asColumn: start_date
                         
                       - name: any_timestamp
                         column: validity_end
                         asColumn: validity_end
    - name: dataos-tool-ottuserdata
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecomltd_ottchurn/ott_userdatasetltd?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-userdata
