version: v1
name: wf-ott-players
type: workflow
tags:
    - ott.player

description: The Job Ingests OTT player data from Blob Storage to icebase
workflow:
  title: OTT Player Load
  dag:
    - name: ott-player
      title: OTT player Dataset
      description:  The Job Ingests OTT player data from Blob Storage to icebase
      spec:
        tags:
          - ott.player
        stack: flare:4.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 6000m
            cores: 2
            memory: 8000m
          executor:
            coreLimit: 6000m
            cores: 2
            instances: 2
            memory: 8000m   
          job:
            explain: true
            inputs:
              - name: player_input
                dataset: dataos://thirdparty01:none/analytics/ott/Player.csv
                format: csv
                options:
                 header: True
                 inferschema: True

            logLevel: INFO
            outputs:
              - name: player
                dataset: dataos://icebase:telecom_ottchurn/ott_player?acl=rw
                format: Iceberg
                options:
                  saveMode: overwrite
            steps:
              - sequence:
                  - name: player
                    sql:  >
                      select * from player_input
                    functions:
                      - name: cleanse_column_names
                      - name: change_column_case
                        case: lower

                      - name: any_timestamp
                        column: session_start
                        asColumn: session_start

    - name: dataos-tool-ottplayer
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_player?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-player