version: v1
name: wf-ott-content-01
type: workflow
workspace: public
description:  The Job Ingests OTT content from GBQ
tags:
  - content
  - ott
workflow:
  title: OTT content load
  dag:
    - name: ott-content
      title: OTT content Dataset
      description: This job ingest data of OTT content from GBQ to icebase
      spec:
        tags:
          - depot
          - ott churn
        stack: flare:3.0
        compute: runnable-default
        flare:
          job:
            inputs:
              - name: content_input
                dataset: dataos://ottbigquery:content/complaintable
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:telco_ott?acl=rw
            steps:
              - sink:
                  - sequenceName: content
                    datasetName: ott_content
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset giv.es details of all OTT content and their corresponding attributes.
                    title: OTT complaints Data
                    tags:
                      - ott
                      - contents
                    outputOptions:
                      saveMode: overwrite
                sequence:
                  - name: content
                    sql: >
                      select * from content_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower
    - name: dataos-tool-ottcontent
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:ott_churn/ott_content_05?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-content