version: v1
name: wf-ott-complaints
type: workflow
workspace: public
description:  The Job Ingests OTT complaints from GBQ
tags:
  - dataos.ott
workflow:
  title: OTT complaints load
  dag:
    - name: ott-complaints
      title: OTT complaints Dataset
      description: This job ingest data of OTT complaints from GBQ to icebase
      spec:
        tags:
          - dataos.ott
        stack: flare:3.0
        compute: runnable-default
        flare:
          job:
            inputs:
              - name: complaints_input
                dataset: dataos://ottbigquery:complaints/complaintable
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:telecom_ottchurn?acl=rw
            steps:
              - sink:
                  - sequenceName: complaints
                    datasetName: ott_complaints
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset gives details of all OTT complaints and their corresponding attributes
                    title: OTT complaints Data
                    tags:
                      - dataos.ott
                    outputOptions:
                      saveMode: overwrite
                sequence:
                  - name: complaints
                    sql: >
                      select * from complaints_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower

                      - name: any_timestamp
                        column: issue_time
                        asColumn: issue_time

                      - name: set_type
                        columns:
                          mobile_number: string
                                          
    - name: dataos-tool-ottcomplaints
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_complaints?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-complaints