version: v1
name: wf-ott-contract
type: workflow
workspace: public
description: The Job Ingests OTT contract from GBQ
tags:
 - dataos.ott
workflow:
 title: OTT contract load
 dag:
   - name: ott-contract
     title: OTT contract Dataset
     description: This job ingest data of OTT contract from GBQ to icebase
     spec:
       tags:
         - dataos.ott
       stack: flare:3.0
       compute: runnable-default
       flare:
         job:
           inputs:
             - name: contract_input
               dataset: dataos://ottbigquery:contract/contractable
           logLevel: INFO
           outputs:
             - name: output01
               depot: dataos://icebase:telecom_ottchurn?acl=rw
           steps:
             - sink:
                 - sequenceName: contract
                   datasetName: ott_contract
                   outputName: output01
                   outputType: Iceberg
                   description: This dataset gives details of all OTT contract and their corresponding attributes
                   title: OTT contract Data
                   tags:
                     - dataos.ott
                   outputOptions:
                     saveMode: overwrite
               sequence:
                 - name: contract
                   sql: >
                     select * from contract_input
                   functions:
                     - name: snake_case
                     - name: change_column_case
                       case: lower

 
                     - name: any_timestamp
                       column: contract_effective_date
                       asColumn: contract_effective_date
                         
                     - name: any_timestamp
                       column: contract_end_date
                       asColumn: contract_end_date                   
   - name: dataos-tool-ottcontract
     spec:
       stack: toolbox
       compute: runnable-default
       toolbox:
         dataset: dataos://icebase:telecom_ottchurn/ott_contract?acl=rw
         action:
           name: set_version
           value: latest
     dependencies:
       - ott-contract