version: v1
name: wf-ott-complaints
type: workflow
tags:
    - ott.complaints

description: This job extracting OTT complaints stored in Blob storage and seamlessly transferring them into Icebase
workflow:
  title: OTT complaints Load
  dag:
    - name: ott-complaints
      title: OTT complaints Dataset
      description:  This job extracting OTT complaints stored in Blob storage and seamlessly transferring them into Icebase
      spec:
        tags:
          - ott.complaints
        stack: flare:4.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 6000m
            cores: 2
            memory: 8000m
          executor:
            coreLimit: 6000m
            cores: 2
            instances: 2
            memory: 8000m   
          job:
            explain: true
            inputs:
              - name: complaints_input
                dataset: dataos://thirdparty01:none/analytics/ott/Complaints.csv
                format: csv
                options:
                 header: True
                 inferschema: True

            logLevel: INFO
            outputs:
              - name: complaints
                dataset: dataos://icebase:telecom_ottchurn/ott_complaints?acl=rw
                format: Iceberg
                options:
                  saveMode: overwrite
            steps:
              - sequence:
                  - name: complaints
                    sql:  >
                      select * from complaints_input
                    functions:
                      - name: cleanse_column_names
                      - name: change_column_case
                        case: lower

    - name: dataos-tool-ottcomplaints
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_complaints?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-complaints