version: v1
name: wf-ott-billing
type: workflow
tags:
    - ott.billing

description: The Job Ingests OTT Billing Data from Blob storage to Icebase
workflow:
  title: OTT billing load
  dag:
    - name: ott-billing
      title: OTT billing Dataset
      description:  The Job Ingests OTT Billing data from Blob storage to Icebase
      spec:
        tags:
          - ott.billing
        stack: flare:4.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 6000m
            cores: 2
            memory: 8000m
          executor:
            coreLimit: 6000m
            cores: 2
            instances: 2
            memory: 8000m   
          job:
            explain: true
            inputs:
              - name: billing_input
                dataset: dataos://thirdparty01:none/analytics/ott/Billing.csv
                format: csv
                options:
                 header: True
                 inferschema: True

            logLevel: INFO
            outputs:
              - name: billing
                dataset: dataos://icebase:telecom_ottchurn/ott_billing?acl=rw
                format: Iceberg
                options:
                  saveMode: overwrite
            steps:
              - sequence:
                  - name: billing
                    sql:  >
                      select * from billing_input
                    functions:
                      - name: cleanse_column_names
                      - name: change_column_case
                        case: lower

    - name: dataos-tool-ottbilling
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_billing?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-billing