version: v1
name: wf-ott-player-02
type: workflow
workspace: public
description:  The Job Ingests OTT player from S3
tags:
  - player
  - ott
workflow:
  title: OTT player load
  schedule:
    cron: "0 */1 * * *"
    concurrencyPolicy: Forbid
  dag:
    - name: ott-player
      title: OTT player Dataset
      description: This job ingest data of OTT player from S3 to icebase
      spec:
        tags:
          - depot
          - ott churn
        stack: flare:3.0
        compute: runnable-default
        flare:
          job:
            explain: true
            streaming:
              batchMode: true
              triggerMode: Once
              checkpointLocation: dataos://icebase:sys01/checkpoint/ott-churn-player/test/player-injest-00002?acl=rw
            inputs:
              - name: player_input
                dataset: dataos://ottbigquery:player/playertable
                format: csv
            logLevel: INFO
            outputs:
              - name: output01
                depot: dataos://icebase:telco_ott?acl=rw
            steps:
              - sink:
                  - sequenceName: player
                    datasetName: ott_player
                    outputName: output01
                    outputType: Iceberg
                    description: This dataset gives details of all OTT player and their corresponding attributes.
                    title: OTT player Data
                    tags:
                      - ott
                      - player
                    outputOptions:
                      saveMode: append
                sequence:
                  - name: player
                    sql: >
                      select * from player_input
                    functions:
                      - name: snake_case
                      - name: change_column_case
                        case: lower

                      - name: any_timestamp
                        column: session_start
                        asColumn: session_start
                                            
    - name: dataos-tool-ottplayer
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telco_ott/ott_player?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-player