version: v1
name: wf-ott-userdata
type: workflow
tags:
    - ott.userdata

description: The Job Ingests OTT users data from Blob storage to icebase
workflow:
  title: OTT Userdata Load
  dag:
    - name: ott-userdata
      title: OTT Userdata Dataset
      description:  The Job Ingests OTT users data from Blob storage to icebase
      spec:
        tags:
          - ott.userdata
        stack: flare:4.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 6000m
            cores: 2
            memory: 8000m
          executor:
            coreLimit: 6000m
            cores: 2
            instances: 2
            memory: 8000m   
          job:
            explain: true
            inputs:
              - name: userdata_input
                dataset: dataos://thirdparty01:none/analytics/ott/Users.csv
                format: csv
                options:
                 header: True
                 inferschema: True

            logLevel: INFO
            outputs:
              - name: userdata
                dataset: dataos://icebase:telecom_ottchurn/ott_userdataset?acl=rw
                format: Iceberg
                options:
                  saveMode: overwrite
            steps:
              - sequence:
                  - name: userdata
                    sql:  >
                      select * from userdata_input
                    functions:
                      - name: cleanse_column_names
                      - name: change_column_case
                        case: lower

                      - name: any_timestamp
                        column: dob
                        asColumn: dob

                      - name: any_timestamp
                        column: start_date
                        asColumn: start_date
                        
                      - name: any_timestamp
                        column: validity_end
                        asColumn: validity_end

    - name: dataos-tool-ottuserdata
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:telecom_ottchurn/ott_userdataset?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - ott-userdata