version: v1
name: wf-billing-quality
type: workflow
tags:
  - ott.billing
description: The job performs metrics calculations and checks on billing data
workflow:
  title: Metrics and checks
  dag:
    - name: ott-billing-quality
      title: Metrics and checks
      description: The job performs metrics calculations and checks on billing data
      spec:
        stack: flare:4.0
        compute: runnable-default
        tags:
          - ott.billing
        title: Metrics and checks
        description: The job performs metrics calculations and checks on billing data
        flare:
          job:
            explain: true
            logLevel: INFO
            inputs:
              - name: ott_billing
                dataset: dataos://icebase:telecom_ottchurn/ott_billing
                format: iceberg
            assertions: 

#Verify whether the value of Customer ID is Unique in database
              - sql: |
                    SELECT
                      count(customerid) count_customerid
                    FROM
                      ott_billing
                    GROUP BY
                      customerid
                test: 
                  - customer_id == 1

#Verify whether the value of Billing ID is Unique in database

              - sql: |
                    SELECT
                      count(billingid) count_billingid
                    FROM
                      ott_billing
                    GROUP BY
                      billingid
                test: 
                  - count_billingid == 1
                
#Verify whether the value of the Billing ID is NOT NULL in the database

              - sql: |
                    SELECT
                    count(billingid) as billing
                    FROM
                    ott_billing
                    WHERE
                    billingid IS NULL
                tests: 
                  - billing == 0 
#Verify whether the value of the Customer ID is NOT NULL in the database

              - sql: |
                    SELECT
                    count(customerid) as customer
                    FROM
                    ott_billing
                    WHERE
                    customerid IS NULL
                tests: 
                  - customer == 0 

          sparkConf:
            - spark.serializer: org.apache.spark.serializer.KryoSerializer
            - spark.sql.shuffle.partitions: "10"
            - spark.memory.storageFraction: "0.1"
            - spark.memory.fraction: "0.1"
            - spark.shuffle.memoryFraction: "0.2"