version: v1
name: wf-b2bdata-quality
type: workflow
tags:
  - dataos.ott
description: The job performs metrics calculations and checks on b2bdata data
workflow:
  title: Metrics and checks
  dag:
    - name: ott-b2bdata-quality
      title: Metrics and checks
      description: The job performs metrics calculations and checks on b2bdata data
      spec:
        stack: flare:3.0
        compute: runnable-default
        tags:
          - dataos.ott
        title: Metrics and checks
        description: The job performs metrics calculations and checks on b2bdata data
        flare:
          job:
            explain: true
            logLevel: INFO
            inputs:
              - name: ott_b2bdata
                dataset: dataos://icebase:telecom_ottchurn/ott_b2bdata
                format: iceberg
            assertions: 

#Verify whether the value of Customer ID is Unique in database

              - sql: |
                    SELECT
                      count(customerid) count_customerid
                    FROM
                      ott_b2bdata
                    GROUP BY
                      customerid
                test: 
                  - count_customerid == 1

#Verify whether the value of the Customer ID is NOT NULL in the database

              - sql: |
                    SELECT
                    count(customerid) as customer
                    FROM
                    ott_b2bdata
                    WHERE
                    customerid IS NULL
                tests: 
                  - customer == 0 
#Verify whether the value of Device ID is Unique in database

              - sql: |
                    SELECT
                      count(deviceid) count_deviceid
                    FROM
                      ott_b2bdata
                    GROUP BY
                      deviceid
                test: 
                  - count_deviceid == 1
              
#Verify whether the value of the Device ID is NOT NULL in the database

              - sql: |
                    SELECT
                    count(deviceid) as device
                    FROM
                    ott_b2bdata
                    WHERE
                    deviceid IS NULL
                tests: 
                  - device == 0 

#Verify whether the value of Partner ID  is Unique in database

              - sql:
                    SELECT 
                      count(partnerid) count_partnerid
                    FROM 
                      ott_b2bdata
                    GROUP BY
                      partnerid
                test:
                  -count_deviceid == 1

#Verify whether the value of the Partner ID is NOT NULL in the database

              - sql: |
                    SELECT
                    count(partnerid) as partner
                    FROM
                    ott_b2bdata
                    WHERE
                    partnerid IS NULL
                tests: 
                  - partner == 0 
#Verify whether the value of Asset ID  is Unique in database
              - sql:
                    SELECT 
                      count(assetid) count_assetid
                    FROM
                      ott_b2bdata
                    GROUP BY 
                      assetid

                test:
                  -count_deviceid == 1 

#Verify whether the value of the Asset ID is NOT NULL in the database

              - sql: |
                    SELECT
                    count(assetid) as asset
                    FROM
                    ott_b2bdata
                    WHERE
                    assetid IS NULL
                tests: 
                  - asset == 0 

#Verify whether the value of the Premium Content in the data base is either Yes or NO 

              - sql: |
                    SELECT
                    CASE
                    WHEN premiumcontent IN ('Yes','No') THEN 1
                    ELSE 0
                    END premium
                    FROM
                    ott_b2bdata
                    GROUP BY
                    1
                    ORDER BY
                    1
                tests: 
                  - premium == 1

          sparkConf:
            - spark.serializer: org.apache.spark.serializer.KryoSerializer
            - spark.sql.shuffle.partitions: "10"
            - spark.memory.storageFraction: "0.1"
            - spark.memory.fraction: "0.1"
            - spark.shuffle.memoryFraction: "0.2"