version: v1
name: wf-player-quality-01
type: workflow
tags:
  - play
  - ott
description: The job performs metrics calculations and checks on player data
workflow:
  title: Metrics and checks
  dag:
    - name: ott-player-quality
      title: Metrics and checks
      description: The job performs metrics calculations and checks on player data
      spec:
        stack: flare:3.0
        compute: runnable-default
        tags:
          - player
          - ott
        title: Metrics and checks
        description: The job performs metrics calculations and checks on player data
        flare:
          job:
            explain: true
            logLevel: INFO
            inputs:
              - name: ott_player_02
                dataset: dataos://icebase:telco_ott/ott_player
                format: iceberg
            assertions: 
            #Verify whether the value of the Event Type is NOT NULL in the database
              - sql: | 
                    SELECT
                    count(event_type) as event
                    FROM
                    ott_player_02
                    WHERE
                    event_type IS NULL
                tests: 
                  - event == 0

            #Verify whether the value of the Session start is not greater than validity date

              - sql: |
                    SELECT
                    CASE
                      WHEN session_start IS NULL THEN 0
                      ELSE 1
                    END session_start
                    FROM
                    ott_player_02
                     WHERE
                    start_position < end_position
                    GROUP BY
                    1
                    ORDER BY
                    1
                tests: 
                  - session_start == 1

            #Verify whether the value of the Premium Content Type in the data base is either Yes or NO

              - sql: |
                    SELECT
                    CASE
                    WHEN premium_content_type IN ('Yes','No') THEN 1
                    ELSE 0
                    END premium
                    FROM
                    ott_player_02
                    GROUP BY
                    1
                    ORDER BY
                    1
                tests: 
                  - premium == 1

            # Verify whether the value of the Start Position is not greater than END Position

              - sql: |
                    SELECT
                    CASE
                      WHEN start_position IS NULL THEN 0
                      ELSE 1
                    END start_position
                    FROM
                    ott_player_02
                    WHERE
                    start_position <> end_position
                    GROUP BY
                    1
                    ORDER BY
                    1
                tests: 
                  - start_position == 1
                  
          sparkConf:
            - spark.serializer: org.apache.spark.serializer.KryoSerializer
            - spark.sql.shuffle.partitions: "10"
            - spark.memory.storageFraction: "0.1"
            - spark.memory.fraction: "0.1"
            - spark.shuffle.memoryFraction: "0.2"