version: v1
name: wf-user-quality
type: workflow
tags:
  - user
  - ott
description: The job performs metrics calculations and  checks on user data
workflow:
  title: Metrics and checks
  dag:
    - name: ott-user-quality
      title: Metrics and checks
      description: The job performs metrics calculations and checks on user data
      spec:
        stack: flare:3.0
        compute: runnable-default
        tags:
          - user
          - ott
        title: Metrics and checks
        description: The job performs metrics calculations and checks on user data
        flare:
          job:
            explain: true
            logLevel: INFO
            inputs:
              - name: ott_userdataset
                dataset: dataos://icebase:telco_ott/ott_userdataset
                format: iceberg
            assertions: 

      #Verify whether the value of the Profile Id is NOT NULL in the database  
      #value is showing 0 here
              - sql: |
                    SELECT
                    count(profile_id) as profile
                    FROM
                    ott_userdataset
                    WHERE
                    profile_id IS NULL
                tests: 
                  - profile == 0 

      #Verify whether the value of the DOB in the database is not greater than current data

              - sql: |
                   SELECT
                    CASE
                    WHEN dob IS NULL THEN 0              
                    ELSE 1
                    END dob
                    FROM
                    ott_userdataset
                    GROUP BY
                    1
                    ORDER BY
                    1
                test: 
                  - dob == 1

      #Verify whether the value of Email is Unique in database.
              - sql: |
                    SELECT
                      count(email) count_email
                    FROM
                      ott_userdataset
                    GROUP BY
                      email
                test: 
                  - count_email == 1

      #Verify whether the value of the start date is not greater than validity date
              - sql: |
                    SELECT
                    CASE
                      WHEN start_date IS NULL THEN 0
                      ELSE 1
                    END start_date
                    FROM
                    ott_userdataset
                     WHERE
                    start_date < validity_end
                    GROUP BY
                    1
                    ORDER BY
                    1
                tests: 
                  - start_date == 1

      #Verify whether the value of the status in the database is either Active or Inactive

              - sql: |
                    SELECT
                    CASE
                    WHEN status IN ('ACTIVE','INACTIVE') THEN 1
                    ELSE 0
                    END stat
                    FROM
                    ott_userdataset
                    GROUP BY
                    1
                    ORDER BY
                    1
                tests: 
                  - stat == 1

#Verify whether the value of the Upgradable in the database is either Yes or NO

              - sql: |
                    SELECT
                    CASE
                    WHEN upgradable IN ('Yes','No') THEN 1
                    ELSE 0
                    END upgrad
                    FROM
                    ott_userdataset
                    GROUP BY
                    1
                    ORDER BY
                    1
                tests: 
                  - upgrad == 1

          sparkConf:
            - spark.serializer: org.apache.spark.serializer.KryoSerializer
            - spark.sql.shuffle.partitions: "10"
            - spark.memory.storageFraction: "0.1"
            - spark.memory.fraction: "0.1"
            - spark.shuffle.memoryFraction: "0.2"