version: v1
name: wf-ott-contract
type: workflow
tags:
  - dataos.ott
description: The job performs metrics calculations and checks on contract data
workflow:
  title: Metrics and checks
  dag:
    - name: ott-contract-quality
      title: Metrics and checks
      description: The job performs metrics calculations and checks on contract data
      spec:
        stack: flare:3.0
        compute: runnable-default
        tags:
          - dataos.ott
        title: Metrics and checks
        description: The job performs metrics calculations and checks on contract data
        flare:
          job:
            explain: true
            logLevel: INFO
            inputs:
              - name: ott_contract
                dataset: dataos://icebase:telecom_ottchurn/ott_contract
                format: iceberg
            assertions: 

#Verify whether the value of Contract ID is Unique in database
              - column: contract_id
                test: 
                 - distinct_count == 1

          sparkConf:
            - spark.serializer: org.apache.spark.serializer.KryoSerializer
            - spark.sql.shuffle.partitions: "10"
            - spark.memory.storageFraction: "0.1"
            - spark.memory.fraction: "0.1"
            - spark.shuffle.memoryFraction: "0.2"