version: v1
name: wf-complaints-quality
type: workflow
tags:
  - dataos.ott
description: The job performs metrics calculations and checks on complaints data
workflow:
  title: Metrics and checks
  dag:
    - name: ott-complaints-quality
      title: Metrics and checks
      description: The job performs metrics calculations and checks on complaints data
      spec:
        stack: flare:3.0
        compute: runnable-default
        tags:
          - dataos.ott
        title: Metrics and checks
        description: The job performs metrics calculations and checks on complaints data
        flare:
          job:
            explain: true
            logLevel: INFO
            inputs:
              - name: ott_complaints
                dataset: dataos://icebase:telecom_ottchurn/ott_complaints
                format: iceberg
            assertions: 

#Verify whether the value of Email ID is Unique in database.

              - column: email_id
                test: 
                 - distinct_count == 1

#Verify whether the value of User Identifier is Unique in database

              - column: user_identifier
                test: 
                 - distinct_count == 1

          sparkConf:
            - spark.serializer: org.apache.spark.serializer.KryoSerializer
            - spark.sql.shuffle.partitions: "10"
            - spark.memory.storageFraction: "0.1"
            - spark.memory.fraction: "0.1"
            - spark.shuffle.memoryFraction: "0.2"